version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.3.2
    - 7.5.2
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.0.3
    - 6.1.0
  - dependency-name: org.flywaydb:flyway-maven-plugin
    versions:
    - 7.3.2
    - 7.5.2
  - dependency-name: org.hibernate:hibernate-entitymanager
    versions:
    - 5.4.27.Final
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.0
