version: '2'
services:
  db:
    image: postgres
    expose:
      - 5432
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=kw

  backend:
    image: caladreas/keep-watching-be
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
        - db