# Meta
site_name: Keep-Watching
site_url: https://joostvdg.github.io/keep-watching
# Copyright
copyright: 'Copyright &copy; 2017 Joost van der Griendt'
repo_name: 'joostvdg/keep-watching'
repo_url: 'https://github.com/joostvdg/keep-watching'

# Pages
pages:
- Home: index.md
- Circle CI: circle-ci.md
- Heroku: heroku.md
- Backend:
    - Spring Boot: backend/spring-boot.md
    - Security: backend/security.md
    - ReactJS: backend/reactjs.md
    - Database: backend/database.md

# Theme
theme: 'material'

# Extra Options
extra:
  palette:
    primary: 'orange'
    accent: 'red'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
