spring:
#    thymeleaf:
#        check-template-location: false
    sql:
        init:
            continue-on-error: true
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:15432/kw
      username: docker
      password: docker

    jooq:
       sql-dialect: POSTGRES

    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: cadc112d448ee253c0b6
                        client-secret: 271a547335a2f7f52d51d76aecd9cc78fdcf79d2
                    facebook:
                        client-id: 1686544878318686
                        client-secret: 3936e2aafc1c13759a35f592bef7ab39
